name: Get latest release version
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs: 
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPOSITORY_SECRET }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/ansible/ansible/releases/latest | jq -r ".tag_name" > VERSION
      - name: Check if file is modified
        id: git-check
        run: |
          MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo "modified=$MODIFIED" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Felix Zimmermann'
          git config --global user.email 'felix.zimmermann.1.de@gmail.com'
          git commit -am "New release version"
          git push
